name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - run: python -m se_mapping_education_math_g8
